---
# tasks file for php
- name: install package php-fpm
  apt:
    name: php-fpm
    state: present
- name: copy php-fpm config
  copy:
    src: www.conf
    dest: /etc/php/8.1/fpm/pool.d/
  notify:
    - Reload php-fpm
- name: make folder for wwwroot
  file:
    path: /opt/php
    state: directory
- name: copy index.php
  copy:
    src: index.php
    dest: /opt/php
- name: Check started service php8.1-fpm
  service:
    name: php8.1-fpm
    state: started
    