- hosts: localhost
  become: yes
  tasks: 
  - name: Create group
    ansible.builtin.group: 
      name: 'superusers'
      state: 'present'
  - name: Create user user1
    ansible.builtin.user:
      name: user1
      state: 'present'
      groups:
        - superusers
  - name: Create user user2
    ansible.builtin.user:
      name: user2
      state: 'present'
      groups:
        - superusers
  - name: Add group to sudoers and validate
    ansible.builtin.lineinfile:
      path: /etc/sudoers
      state: present
      line: '%superusers	ALL=(ALL:ALL) ALL'
      validate: /usr/sbin/visudo -cf %s