- hosts: localhost
  tasks: 
  - name: install docker 
    apt: 
      name: 'docker'
      state: 'present'
  - name: start docker
    service:
      name: 'docker.service'
      state: 'started'
    become: yes