apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sf
  labels:
    app: nginx-sf-label
spec:
  selector:
    matchLabels:
      app: nginx-sf-pod
  replicas: 3 
  template:
    metadata:
      labels:
        app: nginx-sf-pod
    spec:
      containers:
      - name: nginx-sf-container
        image: nginx:1.21.1-alpine
        ports:
          - containerPort: 80
        volumeMounts:
          - name: nginx-config-volume
            mountPath: /etc/nginx
          - name: nginx-secret-volume
            mountPath: /tmp/nginx-secret-volume
          - name: nginx-script-volume
            mountPath: /docker-entrypoint.d/40_create_passwd.sh
            subPath: 40_create_passwd.sh            
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-sf-config
            items:
            - key: nginx.conf
              path: nginx.conf
        - name: nginx-script-volume
          configMap:
            name: nginx-sf-config
            items:
            - key: create_passwd
              path: 40_create_passwd.sh
            defaultMode: 0744
        - name: nginx-secret-volume
          secret:
            secretName: auth-basic
---

apiVersion: v1
kind: Service
metadata:
  name: sf-webserver
spec:
  selector:
    app: nginx-sf-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: v1
kind: Secret
metadata:
  name: auth-basic
type: generic
stringData:
  user1: password1

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-sf-config
data:
  create_passwd: |
    #!/bin/sh
    for file in /tmp/nginx-secret-volume/*; do echo  `basename $file`:`cat $file | cryptpw -m md5`>/tmp/.htpasswd; done
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       80;
          server_name  localhost;
          auth_basic           "Administrator’s Area";
          auth_basic_user_file /tmp/.htpasswd;
          location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
      }
    }

