---
# handlers file for nginx_php

- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
- name: Reload php-fpm
  ansible.builtin.service:
    name: php8.1-fpm
    state: reloaded
