---
# tasks file for nginx_php
- name: install package nginx
  apt:
    name: nginx
    state: present
- name: install package php-fpm
  apt:
    name: php-fpm
    state: present
- name: copy nginx config
  copy:
    src: default
    dest: /etc/nginx/sites-available/default
  notify:
    - Reload nginx
- name: copy php-fpm config
  copy:
    src: www.conf
    dest: /etc/php/8.1/fpm/pool.d
  notify:
    - Reload php-fpm
- name: make folder for wwwroot
  file:
    path: /opt/nginx/ansible
    state: directory
- name: copy index.php
  copy:
    src: index.php
    dest: /opt/nginx/ansible
- name: Check started service php8.1-fpm
  service:
    name: php8.1-fpm
    state: started
- name: Check started service nginx
  service:
    name: nginx
    state: started


        