FROM python:alpine as builder
RUN pip install flask --user psycopg2-binary configparser
FROM alpine
COPY --from=builder /root/.local /root/.local
COPY ./web.py /srv/app/
COPY ./web.conf /srv/app/conf/
COPY --from=builder /usr/local/bin /usr/local/bin
COPY --from=builder /usr/local/include /usr/local/include
COPY --from=builder /usr/local/share /usr/local/share
COPY --from=builder /usr/local/lib/*.so /usr/local/lib/
RUN ln -s  /usr/local/lib/libpython3.10.so /usr/local/lib/libpython3.10.so.1.0
COPY --from=builder /usr/local/lib/pkgconfig /usr/local/lib/pkgconfig
COPY --from=builder /usr/local/lib/python3.10/*.py /usr/local/lib/python3.10/
COPY --from=builder /usr/local/lib/python3.10/collections /usr/local/lib/python3.10/collections
COPY --from=builder /usr/local/lib/python3.10/email /usr/local/lib/python3.10/email
COPY --from=builder /usr/local/lib/python3.10/encodings /usr/local/lib/python3.10/encodings
COPY --from=builder /usr/local/lib/python3.10/html /usr/local/lib/python3.10/html
COPY --from=builder /usr/local/lib/python3.10/http /usr/local/lib/python3.10/http
COPY --from=builder /usr/local/lib/python3.10/importlib /usr/local/lib/python3.10/importlib
COPY --from=builder /usr/local/lib/python3.10/json /usr/local/lib/python3.10/json
COPY --from=builder /usr/local/lib/python3.10/lib-dynload /usr/local/lib/python3.10/lib-dynload
COPY --from=builder /usr/local/lib/python3.10/logging /usr/local/lib/python3.10/logging
COPY --from=builder /usr/local/lib/python3.10/urllib /usr/local/lib/python3.10/urllib
WORKDIR /srv/app
ENV PATH=/root/.local:$PATH
CMD ["python3","web.py"]