version: '3.9'

services:
  php:
    build: .
    networks:
      - net
    volumes:
     - type: bind
       source: ./www
       target: /var/www
    healthcheck:
      test: curl http://nginx | grep "works"
      interval: 5s
      timeout: 5s
      retries: 5
     
  nginx:
    image: "nginx"
    networks:
      - net
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./nginx
        target: /etc/nginx/conf.d
      - type: bind
        source: ./www
        target: /var/www
networks:
  net:

