FROM python:alpine as builder
RUN pip install flask --user psycopg2-binary configparser
FROM python:alpine
COPY --from=builder /root/.local /root/.local
WORKDIR /srv/app
ENV PATH=/root/.local:$PATH
CMD ["python3","web.py"]